name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1
          cache: true
      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter build apk --debug
      - uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.date.outputs.date }}"
          artifacts: build/app/outputs/flutter-apk/app-debug.apk
        if: ${{ github.event_name == 'push' }}
